project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Home"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Ccccraz
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

resources: 
  - CNAME